coverage:
  status:
    project:
      default:
        # Allow decreasing 5% of total coverage to avoid noise.
        target: auto
        threshold: 5%
    patch:
      default:
        target: 50%
        base: pr
        only_pulls: true
