name: CI
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version:
          - 1.15
          - 1.16
          - 1.17
          - 1.18
          - 1.19
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Vet
        run: go vet ./...
      - name: Test
        run: go test -v -run "^TestProvider$/^DelayedHTTPErrorRetry$" -count 100 -failfast

  examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Install deps
        run: |
          sudo apt-get update -qq
          sudo apt-get install --no-install-recommends -y \
            libgstreamer1.0-dev \
            libgstreamer-plugins-base1.0-dev

      - name: Build example
        working-directory: examples
        run: go build ./...
