name: CI
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version:
          - 1.15
          - 1.16
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Vet
        run: go vet ./...
      - name: Test
        run: go test ./... -v -coverprofile=cover.out -covermode atomic -coverpkg ./...
      - name: Build example
        working-directory: examples
        run: go build ./...

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./cover.out
